theme: jekyll-theme-leap-day

title: Stef Czischek
description: Assistant Professor at University of Ottawa
banner: Artificial and Physically Realizable Intelligence for Quantum at uOttawa - APRIQuOt
